/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class DanhMuc extends javax.swing.JFrame {

    /**
     * Creates new form DanhMuc
     */
    public DanhMuc() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(360, 640);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        m_letter1 = new javax.swing.JTextField();
        m_letter2 = new javax.swing.JTextField();
        m_letter3 = new javax.swing.JTextField();
        m_letter4 = new javax.swing.JTextField();
        m_letter5 = new javax.swing.JTextField();
        m_letter6 = new javax.swing.JTextField();
        m_letter7 = new javax.swing.JTextField();
        m_letter8 = new javax.swing.JTextField();
        m_letter9 = new javax.swing.JTextField();
        m_letter10 = new javax.swing.JTextField();
        m_letter11 = new javax.swing.JTextField();
        m_letter12 = new javax.swing.JTextField();
        m_letter13 = new javax.swing.JTextField();
        m_letter14 = new javax.swing.JTextField();
        m_letter15 = new javax.swing.JTextField();
        m_quayLaiBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 640));
        setMinimumSize(new java.awt.Dimension(360, 640));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(220, 220, 245));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(220, 220, 245));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFocusCycleRoot(true);
        jScrollPane1.setFocusTraversalPolicyProvider(true);

        jPanel3.setBackground(new java.awt.Color(220, 220, 245));
        jPanel3.setForeground(new java.awt.Color(220, 220, 245));

        m_letter1.setEditable(false);
        m_letter1.setBackground(new java.awt.Color(220, 220, 245));
        m_letter1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter1.setText("Bức thư thứ 1");
        m_letter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                m_letter1MousePressed(evt);
            }
        });

        m_letter2.setEditable(false);
        m_letter2.setBackground(new java.awt.Color(220, 220, 245));
        m_letter2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter2.setText("Bức thư thứ 2");
        m_letter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_letter2MouseClicked(evt);
            }
        });

        m_letter3.setEditable(false);
        m_letter3.setBackground(new java.awt.Color(220, 220, 245));
        m_letter3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter3.setText("Bức thư thứ 3");

        m_letter4.setEditable(false);
        m_letter4.setBackground(new java.awt.Color(220, 220, 245));
        m_letter4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter4.setText("Bức thư thứ 4");

        m_letter5.setEditable(false);
        m_letter5.setBackground(new java.awt.Color(220, 220, 245));
        m_letter5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter5.setText("Bức thư thứ 5");

        m_letter6.setEditable(false);
        m_letter6.setBackground(new java.awt.Color(220, 220, 245));
        m_letter6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter6.setText("Bức thư thứ 6");

        m_letter7.setEditable(false);
        m_letter7.setBackground(new java.awt.Color(220, 220, 245));
        m_letter7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter7.setText("Bức thư thứ 7");

        m_letter8.setEditable(false);
        m_letter8.setBackground(new java.awt.Color(220, 220, 245));
        m_letter8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter8.setText("Bức thư thứ 8");

        m_letter9.setEditable(false);
        m_letter9.setBackground(new java.awt.Color(220, 220, 245));
        m_letter9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter9.setText("Bức thư thứ 9");

        m_letter10.setEditable(false);
        m_letter10.setBackground(new java.awt.Color(220, 220, 245));
        m_letter10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter10.setText("Bức thư thứ 10");
        m_letter10.setToolTipText("");

        m_letter11.setEditable(false);
        m_letter11.setBackground(new java.awt.Color(220, 220, 245));
        m_letter11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter11.setText("Bức thư thứ 11");

        m_letter12.setEditable(false);
        m_letter12.setBackground(new java.awt.Color(220, 220, 245));
        m_letter12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter12.setText("Bức thư thứ 12");

        m_letter13.setEditable(false);
        m_letter13.setBackground(new java.awt.Color(220, 220, 245));
        m_letter13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter13.setText("Bức thư thứ 13");

        m_letter14.setEditable(false);
        m_letter14.setBackground(new java.awt.Color(220, 220, 245));
        m_letter14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter14.setText("Bức thư thứ 14");

        m_letter15.setEditable(false);
        m_letter15.setBackground(new java.awt.Color(220, 220, 245));
        m_letter15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_letter15.setText("Bức thư thứ 15");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(m_letter1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter7, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter8, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter9, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter10, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter11, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter12, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter13, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter14, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(m_letter15, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(m_letter1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(m_letter15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 51, -1, 500));

        m_quayLaiBtn.setBackground(new java.awt.Color(204, 204, 255));
        m_quayLaiBtn.setText("Quay lại");
        m_quayLaiBtn.setContentAreaFilled(false);
        m_quayLaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_quayLaiBtnActionPerformed(evt);
            }
        });
        jPanel1.add(m_quayLaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\bigger\\37.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(374, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_quayLaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_quayLaiBtnActionPerformed
        // TODO add your handling code here:
        new TrangChu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_quayLaiBtnActionPerformed

    private void m_letter1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_letter1MousePressed
        // TODO add your handling code here:
        new Letter1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_letter1MousePressed

    private void m_letter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_letter2MouseClicked
        // TODO add your handling code here:
        new Letter2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_letter2MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DanhMuc().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_letter1;
    private javax.swing.JTextField m_letter10;
    private javax.swing.JTextField m_letter11;
    private javax.swing.JTextField m_letter12;
    private javax.swing.JTextField m_letter13;
    private javax.swing.JTextField m_letter14;
    private javax.swing.JTextField m_letter15;
    private javax.swing.JTextField m_letter2;
    private javax.swing.JTextField m_letter3;
    private javax.swing.JTextField m_letter4;
    private javax.swing.JTextField m_letter5;
    private javax.swing.JTextField m_letter6;
    private javax.swing.JTextField m_letter7;
    private javax.swing.JTextField m_letter8;
    private javax.swing.JTextField m_letter9;
    private javax.swing.JToggleButton m_quayLaiBtn;
    // End of variables declaration//GEN-END:variables
}
