/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import controller.IOFileColor;
import controller.IOFileFont;
import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.green;
import static java.awt.Color.red;
import java.awt.Font;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author PC
 */
public class Letter1 extends javax.swing.JFrame {

    /**
     * Creates new form Letter1
     */
    private Integer fontSize;
    private String font;
    Color color;
    private int style;
    private Font f;
    private String bgPath;
    public Letter1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(360, 640);
        JScrollPane1.getViewport().setOpaque(false);
        JScrollPane1.setOpaque(false);
        m_letterTP1.setOpaque(false); 
        m_letterTP1.setBackground(new Color(0,0,0,0));
        
        fontSize=IOFile.doc("src/controller/size.txt");
        font=IOFileFont.doc("src/controller/font.txt");
        color=IOFileColor.doc("src/controller/color.DAT");
        style=IOFile.doc("src/controller/style.txt");
        //System.out.println(style);
        if(style==0) {
            f=new Font(font,Font.PLAIN,fontSize);
        }
        else if(style==1) {
            f=new Font(font,Font.BOLD,fontSize);
        }
        else if(style==2) {
            f=new Font(font,Font.ITALIC,fontSize);
        }
        
        m_letterTP1.setFont(f);
        m_letterTP1.setForeground(color);
        
        bgPath = IOFileFont.doc("src/controller/BG.txt");
        m_BG.setIcon(new ImageIcon(bgPath));
        
        //m_letterTP1.setContentAreaFilled(false);
                
        //m_danhMucBtn.setOpaque(false);
        //m_danhMucBtn.setContentAreaFilled(false);
        //m_danhMucBtn.setBorderPainted(true);
                
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        m_anhCoSan = new javax.swing.JMenuItem();
        m_taiAnhLen = new javax.swing.JMenuItem();
        m_chonAnh = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        m_bg1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        JScrollPane1 = new javax.swing.JScrollPane();
        m_letterTP1 = new javax.swing.JTextArea();
        m_quayLaiBtn = new javax.swing.JToggleButton();
        m_fontApp = new javax.swing.JLabel();
        m_picture = new javax.swing.JLabel();
        m_BG = new javax.swing.JLabel();

        m_anhCoSan.setText("Ảnh có sẵn");
        m_anhCoSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_anhCoSanActionPerformed(evt);
            }
        });
        jPopupMenu1.add(m_anhCoSan);

        m_taiAnhLen.setText("Tải ảnh lên");
        m_taiAnhLen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_taiAnhLenMouseClicked(evt);
            }
        });
        m_taiAnhLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_taiAnhLenActionPerformed(evt);
            }
        });
        jPopupMenu1.add(m_taiAnhLen);

        m_chonAnh.setMinimumSize(new java.awt.Dimension(340, 650));
        m_chonAnh.setModal(true);

        jPanel3.setMinimumSize(new java.awt.Dimension(340, 650));
        jPanel3.setPreferredSize(new java.awt.Dimension(340, 650));

        m_bg1.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\1.jpg")); // NOI18N
        m_bg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_bg1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\2.jpg")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\3.jpg")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\4.jpg")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\5.jpg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\6.jpg")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\7.jpg")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\8.jpg")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\small\\9.jpg")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jToggleButton1.setText("Ok");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(m_bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_bg1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout m_chonAnhLayout = new javax.swing.GroupLayout(m_chonAnh.getContentPane());
        m_chonAnh.getContentPane().setLayout(m_chonAnhLayout);
        m_chonAnhLayout.setHorizontalGroup(
            m_chonAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        m_chonAnhLayout.setVerticalGroup(
            m_chonAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JScrollPane1.setBackground(new java.awt.Color(178, 251, 188));
        JScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        JScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        JScrollPane1.setEnabled(false);
        JScrollPane1.setFocusable(false);
        JScrollPane1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 14)); // NOI18N
        JScrollPane1.setOpaque(false);
        JScrollPane1.setVerifyInputWhenFocusTarget(false);
        JScrollPane1.setWheelScrollingEnabled(false);

        m_letterTP1.setEditable(false);
        m_letterTP1.setBackground(new java.awt.Color(204, 255, 204));
        m_letterTP1.setColumns(20);
        m_letterTP1.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        m_letterTP1.setRows(30);
        m_letterTP1.setText("#1\n\n\"Thời gian thay đổi, lòng người cũng\n thay đổi, cuộc sống của chúng ta\n tựa như một bộ phim điện ảnh\n không chiếu lại thêm lần nào nữa, \ncó những thứ dù cho chúng ta có \ncố gắng đến như thế nào đi nữa\n thì cũng chẳng bao giờ trở lại \nđược như xưa. Trên đời này \ncái khoảng cách xa nhất không phải\n là yêu, chẳng phải là hận,\n mà là những người quen biết nhau\n dần trở nên xa lạ với nhau.\"");
        m_letterTP1.setAutoscrolls(false);
        m_letterTP1.setOpaque(false);
        m_letterTP1.setRequestFocusEnabled(false);
        m_letterTP1.setVerifyInputWhenFocusTarget(false);
        JScrollPane1.setViewportView(m_letterTP1);

        jPanel1.add(JScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 520));

        m_quayLaiBtn.setText("Quay lại");
        m_quayLaiBtn.setContentAreaFilled(false);
        m_quayLaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_quayLaiBtnActionPerformed(evt);
            }
        });
        jPanel1.add(m_quayLaiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        m_fontApp.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        m_fontApp.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\icon\\icons8-fonts-app-48.png")); // NOI18N
        m_fontApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_fontAppMouseClicked(evt);
            }
        });
        jPanel1.add(m_fontApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        m_picture.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\icon\\icons8-picture-32.png")); // NOI18N
        m_picture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pictureMouseClicked(evt);
            }
        });
        jPanel1.add(m_picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        m_BG.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\LetterBG\\resized\\6.jpg")); // NOI18N
        jPanel1.add(m_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 374, 677);
    }// </editor-fold>//GEN-END:initComponents

    private void m_quayLaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_quayLaiBtnActionPerformed
        // TODO add your handling code here:
        new DanhMuc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_quayLaiBtnActionPerformed

    private void m_fontAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_fontAppMouseClicked
        // TODO add your handling code here:
        //jPopupMenu1.show(m_fontApp, evt.getX(), evt.getY());
        fontSize=IOFile.doc("src/controller/size.txt");
        //System.out.println(fontSize);
        Font f=new Font("Segue UI",Font.PLAIN,fontSize);
        m_letterTP1.setFont(f);
        new SettingFont().setVisible(true);
        //this.dispose();

//        m_settingFont.setVisible(true);
//        m_settingFont.setLocationRelativeTo(null);
//        m_settingFont.setSize(320, 560);
        
    }//GEN-LAST:event_m_fontAppMouseClicked

    private void m_taiAnhLenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_taiAnhLenMouseClicked
        // TODO add your handling code here:
//        System.out.println(1);
//        JFileChooser fileChooser=new JFileChooser();
//        FileNameExtensionFilter imageFilter=new FileNameExtensionFilter("Hinh anh", "jpg","png");
//        fileChooser.setFileFilter(imageFilter);
//        fileChooser.setMultiSelectionEnabled(false);
//        System.out.println(1);
//        
//        int x=fileChooser.showDialog(this, "Chon file");
//        if(x==JFileChooser.APPROVE_OPTION) {
//            File f=fileChooser.getSelectedFile();
//            
//            m_BG.setIcon(new ImageIcon(f.getAbsolutePath()));
//        }
    }//GEN-LAST:event_m_taiAnhLenMouseClicked

    private void m_pictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pictureMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.show(m_fontApp, evt.getX(), evt.getY());
    }//GEN-LAST:event_m_pictureMouseClicked

    private void m_taiAnhLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_taiAnhLenActionPerformed
        // TODO add your handling code here:
        File f1= new File("src/controller/BG.txt");
        if (f1.exists()) {
            bgPath = IOFileFont.doc("src/controller/BG.txt");
            //System.out.println(fontSize);
        }
        
        m_BG.setIcon(new ImageIcon(bgPath));
        
        
        JFileChooser fileChooser=new JFileChooser();
        FileNameExtensionFilter imageFilter=new FileNameExtensionFilter("Hinh anh", "jpg","png");
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setMultiSelectionEnabled(false);
        
        
        int x=fileChooser.showDialog(this, "Chon file");
        if(x==JFileChooser.APPROVE_OPTION) {
            File f=fileChooser.getSelectedFile();
            
            m_BG.setIcon(new ImageIcon(f.getAbsolutePath()));
            IOFileFont.viet("src/controller/BG.txt", f.getAbsolutePath());
            
        }
    }//GEN-LAST:event_m_taiAnhLenActionPerformed

    private void m_anhCoSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_anhCoSanActionPerformed
        // TODO add your handling code here:
        m_chonAnh.setLocationRelativeTo(null);
        m_chonAnh.setVisible(true);
        m_chonAnh.setLocationRelativeTo(null);
    }//GEN-LAST:event_m_anhCoSanActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        m_chonAnh.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void m_bg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_bg1MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/1.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_m_bg1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/2.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/3.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/4.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/5.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/6.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/7.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/8.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        bgPath="D:/Data ProPTIT/JavaApp/BG/bigger/9.jpg";
        m_BG.setIcon(new ImageIcon(bgPath));
        IOFileFont.viet("src/controller/BG.txt", bgPath);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Letter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Letter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Letter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Letter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Letter1().setVisible(true);
//            }
//        });
//    }

    public JTextArea getM_letterTP1() {
        return m_letterTP1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel m_BG;
    private javax.swing.JMenuItem m_anhCoSan;
    private javax.swing.JLabel m_bg1;
    private javax.swing.JDialog m_chonAnh;
    private javax.swing.JLabel m_fontApp;
    private javax.swing.JTextArea m_letterTP1;
    private javax.swing.JLabel m_picture;
    private javax.swing.JToggleButton m_quayLaiBtn;
    private javax.swing.JMenuItem m_taiAnhLen;
    // End of variables declaration//GEN-END:variables
}
