/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import controller.IOFileColor;
import controller.IOFileFont;
import java.awt.Color;
import java.awt.Font;
import static java.awt.font.TextAttribute.FONT;
import java.io.File;
import javax.swing.JColorChooser;
import javax.swing.text.Style;

/**
 *
 * @author PC
 */
public class SettingFont extends javax.swing.JFrame {

    /**
     * Creates new form SettingFont
     */
    private Integer fontSize;
    private String font;
    private Color color;
    private int style;
    public SettingFont() {
        initComponents();
        this.setLocationRelativeTo(null);
        readData();
        //writeData();
    }
    public void readData() {
        File f1= new File("src/controller/size.txt");
        if (f1.exists()) {
            fontSize = IOFile.doc("src/controller/size.txt");
            //System.out.println(fontSize);
        }
        File f2= new File("src/controller/font.txt");
        if (f2.exists()) {
            font = IOFileFont.doc("src/controller/font.txt");
            //System.out.println(fontSize);
        }
        File f3= new File("src/controller/color.DAT");
        if (f3.exists()) {
            color = IOFileColor.doc("src/controller/color.DAT");
            //System.out.println(fontSize);
        }
        File f4= new File("src/controller/style.txt");
        if (f4.exists()) {
            style = IOFile.doc("src/controller/style.txt");
            //System.out.println(fontSize);
        }
    }
    public void writeData() {
        String selected=String.valueOf(m_coChuCBx.getSelectedItem());
        int size=Integer.parseInt(selected);
        IOFile.viet("src/controller/size.txt", size);
        
        String font1=String.valueOf(m_fontChu.getSelectedItem());
        IOFileFont.viet("src/controller/font.txt", font1);
        
        IOFileColor.viet("src/controller/color.DAT", color);
        
        style=m_style.getSelectedIndex();
        IOFile.viet("src/controller/style.txt", style);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        m_coChuCBx = new javax.swing.JComboBox<>();
        m_okBtn = new javax.swing.JToggleButton();
        m_cancelBtn = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        m_font = new javax.swing.JLabel();
        m_fontChu = new javax.swing.JComboBox<>();
        m_fontStyle = new javax.swing.JLabel();
        m_style = new javax.swing.JComboBox<>();
        m_color = new javax.swing.JLabel();
        m_colorChose = new javax.swing.JTextField();
        m_preview = new javax.swing.JTextField();
        m_previewBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Size");

        m_coChuCBx.setMaximumRowCount(10);
        m_coChuCBx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "92", "94", "95", "96", "97", "98", "99", "100" }));
        m_coChuCBx.setToolTipText("Chọn\n");

        m_okBtn.setText("Ok");
        m_okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_okBtnActionPerformed(evt);
            }
        });

        m_cancelBtn.setText("Cancel");

        jToggleButton1.setText("Quay lại");
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        m_font.setText("Font ");

        m_fontChu.setMaximumRowCount(10);
        m_fontChu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Bahnschrift", "Calibri", "Calibri Light", "Cambria", "Cambria Math", "Candara", "Cascadia Code", "Cascadia Mono", "Consolas", "Constantia", "Corbel", "Corbel Light", "Corbel New", "Dialog", "DialogInput", "Microsoft Sans Serif", "Palatino Linotype", "SansSerif", "Segoe UI", "Segoe UI Black", "Segoe UI Light", "Segoe UI Semibold", "Segoe UI Semilight", "Serif", "Sitka Banner", "Sitka Display", "Sitka Heading", "Sitka Small", "Sitka Subheading", "Sitka Text", "Tahoma", "Times New Roman", "Verdana", " " }));

        m_fontStyle.setText("Font Style");

        m_style.setMaximumRowCount(3);
        m_style.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plain", "Bold", "Italic", " ", " " }));

        m_color.setText("Color");

        m_colorChose.setEditable(false);
        m_colorChose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_colorChoseMouseClicked(evt);
            }
        });

        m_preview.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m_preview.setText("Hello World");
        m_preview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_previewMouseClicked(evt);
            }
        });

        m_previewBtn.setText("Preview");
        m_previewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_previewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_color)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(m_fontStyle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(m_font, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_fontChu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_coChuCBx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_style, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_colorChose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(105, Short.MAX_VALUE)
                        .addComponent(m_okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(m_cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_preview)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(m_previewBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_coChuCBx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_fontChu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_font, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_style, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_fontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_color)
                    .addComponent(m_colorChose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(m_previewBtn)
                .addGap(18, 18, 18)
                .addComponent(m_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_cancelBtn)
                    .addComponent(m_okBtn))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 314, 537);
    }// </editor-fold>//GEN-END:initComponents

    private void m_okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_okBtnActionPerformed

        writeData(); 
        new Letter1().setVisible(true);
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_m_okBtnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void m_colorChoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_colorChoseMouseClicked
        // TODO add your handling code here:
        color=JColorChooser.showDialog(this, "Chon mau", Color.BLACK);
        m_colorChose.setBackground(color);
        
    }//GEN-LAST:event_m_colorChoseMouseClicked

    private void m_previewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_previewMouseClicked
        // TODO add your handling code here:
        readData();
        //writeData();
        Font f;
        if(style==0) {
            f=new Font(font,Font.PLAIN,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
        else if(style==1) {
            f=new Font(font,Font.BOLD,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
        else if(style==2) {
            f=new Font(font,Font.ITALIC,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
        
        
    }//GEN-LAST:event_m_previewMouseClicked

    private void m_previewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_previewBtnActionPerformed
        // TODO add your handling code here:
        writeData();
        readData();
        //writeData();
        Font f;
        if(style==0) {
            f=new Font(font,Font.PLAIN,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
        else if(style==1) {
            f=new Font(font,Font.BOLD,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
        else if(style==2) {
            f=new Font(font,Font.ITALIC,fontSize);
            m_preview.setFont(f);
            m_preview.setForeground(color);
        }
    }//GEN-LAST:event_m_previewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SettingFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SettingFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SettingFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SettingFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SettingFont().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton m_cancelBtn;
    private javax.swing.JComboBox<String> m_coChuCBx;
    private javax.swing.JLabel m_color;
    private javax.swing.JTextField m_colorChose;
    private javax.swing.JLabel m_font;
    private javax.swing.JComboBox<String> m_fontChu;
    private javax.swing.JLabel m_fontStyle;
    private javax.swing.JToggleButton m_okBtn;
    private javax.swing.JTextField m_preview;
    private javax.swing.JToggleButton m_previewBtn;
    private javax.swing.JComboBox<String> m_style;
    // End of variables declaration//GEN-END:variables
}

