/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(360, 640);
        //m_danhMucBtn.setOpaque(false);
        //m_danhMucBtn.setContentAreaFilled(false);
        //m_danhMucBtn.setBorderPainted(true);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        m_danhMucBtn = new javax.swing.JToggleButton();
        m_myQuote = new javax.swing.JToggleButton();
        m_no = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(360, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_danhMucBtn.setBackground(new java.awt.Color(204, 204, 255));
        m_danhMucBtn.setText("Danh mục");
        m_danhMucBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_danhMucBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_danhMucBtnActionPerformed(evt);
            }
        });
        jPanel1.add(m_danhMucBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 190, 50));

        m_myQuote.setBackground(new java.awt.Color(204, 204, 255));
        m_myQuote.setText("Tạo Quote");
        m_myQuote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_myQuoteActionPerformed(evt);
            }
        });
        jPanel1.add(m_myQuote, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 190, 50));

        m_no.setBackground(new java.awt.Color(204, 204, 255));
        m_no.setText("Viết chữ lên ảnh");
        m_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_noActionPerformed(evt);
            }
        });
        jPanel1.add(m_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Data ProPTIT\\JavaApp\\BG\\rsz_125.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void m_danhMucBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_danhMucBtnActionPerformed
        // TODO add your handling code here:
        new DanhMuc().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_danhMucBtnActionPerformed

    private void m_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_noActionPerformed
        // TODO add your handling code here:
        new EditImage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_noActionPerformed

    private void m_myQuoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_myQuoteActionPerformed
        // TODO add your handling code here:
        new MyQuote().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_m_myQuoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton m_danhMucBtn;
    private javax.swing.JToggleButton m_myQuote;
    private javax.swing.JToggleButton m_no;
    // End of variables declaration//GEN-END:variables
}
